general:
  host: localhost:3000
  per_page: 10
  
  videos:
    short_description_length: 40

formats:
  flv-h264:
    name: FLV H264
    format: flv
    options:
      vcodec: libx264
      vpre:
      acodec:
  flv-h263:
    name: FLV H263/Soreson
    format: flv
    options:      

publishers:
  youtube:
    username: muller.mem@gmail.com
    password: S1ndeL%google%1988
    api_key: AI39si4UAHNrQFg7GXEgFt1AagGHyFMCYRi4ofOSh275Jrph1yppiFkT1AW_1j6GiUceKQVO8aqWtk1SHlAIOigAboUrlOY5Ng
      
archiver:
  folder:
  username: 
  hostname: 
  identity: 
  
    
manager:
    