general:
  host: localhost:3000
  per_page: 10
  media_types: videos streams
  users_class: Application  
  videos:
    short_description_length: 40

formats:
  flv-h264:
    name: FLV H264
    format: flv
    options:
      vcodec: libx264 -vpre hq -crf 26
      threads: 4
      acodec: libfaac -ab 128k
      
  flv-h263:
    name: FLV H263/Soreson
    format: flv
    options:
      ab: 256k
      ar: 44100
      vb: 512k
      #r: 30       

publishers:
  youtube:
    username: muller.mem@gmail.com
    password: S1ndeL%google%1988
    api_key: AI39si4UAHNrQFg7GXEgFt1AagGHyFMCYRi4ofOSh275Jrph1yppiFkT1AW_1j6GiUceKQVO8aqWtk1SHlAIOigAboUrlOY5Ng
      
archiver:
  folder:
  username: 
  hostname: 
  identity: 
  
    
manager:
    