general:
  videos:
    short_description_length: 40

formats:
  flv-hd:
    resolution: 960x540
    format: flv
  flv-mq: 
    resolution: 480x270
    format: flv

publishers:
  youtube:
    username:
    password:
    api_key:
  mover:
    folder:  